### ISSUE TITLE
option to exclude certain files from search (by filename)

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#27]
In my note base I use the navigate package which allows me to jump to a note when its filename is part of the text-body of another note, e.g. I mark [[link]] and press a shortcut, so that link.txt is opened immediately.

This only works when the link.txt is in the same directory. So I keep all my notes in one directory, also my #tag.txt notes, which contain lists of all notes that contain a certain #tag. 

I do not want these notes to be displayed at the top of the search results. Is there an option to exclude notes with a certain filename from search? (Before textual velocity I used docfetcher, which allowed me to exclude all notes stasrting with # from indexing)

**Comment by viddo** [comment]
At the moment one can filter out files by these two core settings:
![screen shot 2016-10-05 at 13 05 57](https://cloud.githubusercontent.com/assets/978461/19129576/9f6c1f92-8afc-11e6-897f-3a5ead9f04ab.png)
Unfortunately this means that any custom names you'd there would be ignored by other core packages.

The proper solution here would be to add some config settings in addition to the defaults I'd say, e.g.
- Exclude VCS ignored path (instead of the core setting)
- Ignore names defined in the core setting (boolean/checkbox)
- Custom ignored names/patterns (string, complementary to the core setting)

Should be fairly easy to add though, unless someone else beats me to it I'll solve it soon enough.
