### ISSUE TITLE
Note interlinking

### ISSUE THREAD

**Issue by xHN35RQ** [viddo/atom-textual-velocity#33]
Are you considering adding a note interlinking functionality? Or is this something that should be provided by another package? At this point I think a basic note interlink functionality would be useful, but allow it to be toggled to allow users to install other plugins for more advanced interlinking. (for example, my [atom-plumber](https://github.com/xHN35RQ/atom-plumber) package which provides regex-based navigation)

For reference, here is how nvatom handled these links: https://github.com/seongjaelee/nvatom/blob/master/lib/interlink.coffee

**Comment by viddo** [comment]
Yes, and yes I think it makes more sense for that functionality to be the responsibility of another/separate package.

My rough, not so developed yet, idea here would be to offer some service API (like there already are for the columns etc.), so other packages can leverage that this package have an in-memory data structure rather than each to do their own note files handling.

Thanks for the links btw, they'll come handy when tackling this issue (I had planned to do that a little further head, would like to close the other open issues first).

**Comment by xHN35RQ** [comment]
related: https://github.com/dansheffler/zettelkasten-wiki/

**Comment by xHN35RQ** [comment]
closing since this is well provided by other packages

**Comment by viddo** [comment]
👍
