### ISSUE TITLE
allow different search priorities

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#34]
Apart from allowing for users to prioritize Title-matches in search, I would really appreciate an option to prioritize "Density" of the search results. So instead of showing the notes first with the most matches, show those first which have most matches per characters/word count...
For anyone who keeps longer articles (containing the same words that I use to search shorter notes) as part of his note directory, this would be great.

**Comment by viddo** [comment]
The results are already [sorted by "score"](https://github.com/viddo/atom-textual-velocity/blob/edc4037038c5683fa8b5dfc6a82a498874d9c8c9/lib/interactor.js#L65-L68) which sounds similar to how you define "density". From the [search library docs (sifter.js)](https://github.com/brianreavis/sifter.js/blob/master/README.md):

> - Smart scoring.
>
>     Items are scored / sorted intelligently depending on where a match is found in the string (how close to the beginning) and what percentage of the string matches.
> …
> sort | array | An array of fields to sort by. Each item should be an object containing at least a "field" property. Optionally, direction can be set to "asc" or "desc". The order of the array defines the sort precedence.


So perhaps the change there should be to always sort by descending order (highest score first), and have that as the 1st sort priority, with the possibility to control that by a config setting? Would that solve it, you think? 
Since the search/sorting falls in the responsibility of the search library (sifter in this case), I'm considering whether this kind of feature request should be moved there otherwise.

Also, I think this is somewhat related to #26, so probably will tackle both this and that issue at the same time.

**Comment by capcionista** [comment]
I'm really sorry. I have not realized that the arrow below the search field not only controls the sorting of the names when the search field is empty, but also search results.
When you switch it to DOWN-ARROW, it shows the search results as you described. This should be made default priority. This also considers title-matches as a priority (as they are closest to the beginning of the string) - so #26 seems to be solved at least to my satisfaction as well.

**Comment by viddo** [comment]
> I'm really sorry. I have not realized that the arrow below the search field not only controls the sorting of the names when the search field is empty, but also search results.

Don't be sorry! Actually, this might highlight a usability issue. Do you think the sorting could be indicated in another way to make this more obvious?

> When you switch it to DOWN-ARROW, it shows the search results as you described. This should be made default priority. 

It's [already the default](https://github.com/viddo/atom-textual-velocity/blob/master/lib/default-config.js#L29), but only unless you had a value already (from a earlier version perhaps… don't remember if I ever changed it).

I still think #26 is interesting so I'll leave it open for now.

If you think this issue is resolved feel free to close it!
