### ISSUE TITLE
Syntax Style in Preview

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#40]
It would be great if the preview would include syntax styling, most importantly probably markdown.

**Comment by viddo** [comment]
Yes it would be nice. Ideally it would be nice to just use the [default text editor](https://github.com/atom/atom/blob/4d2641962e6b9d70948792f7f1d6f7bf46725e38/src/text-editor.coffee), but remove all the slow parts that's not necessary for the sake of previewing an item. 

That said, it's not a trivial task, it requires a lot of time to learn how the text-editor works internally and figure out what and how to remove the parts that's not necessary. Until someone takes that time I implemented the preview with the primary goal of making note navigation/search simple and fast (_is this the note I'm looking for?_).

**Comment by gotjoshua** [comment]
this issue is exactly the reason that i forked the project.

I am seriously hoping that this is false:

> it requires a lot of time to learn how the text-editor works internally and figure out what and how to remove the parts that's not necessary

I just want to check if markdown-preview-plus is installed and create an instance of that instead of the HTMLElement on line 8 in preview-element.js

Seems like [markdown-preview-plus-opener.coffee](https://github.com/nick-f/markdown-preview-plus-opener/blob/master/lib/markdown-preview-plus-opener.coffee) has most of the syntax that would be needed.

My problem is i am totally new to coffeescript and textual-velocity is in js...

What to do?

**Comment by viddo** [comment]
@gotjoshua The package you referenced [_Opens the markdown-preview-plus pane automatically when a markdown file is opened_](https://github.com/nick-f/markdown-preview-plus-opener). That relies on a normal text-editor to be opened so _an additional pane_ is opened to _preview the rendered markdown output_. This is not the same kind of _preview_ that this issue is about.

> I just want to check if markdown-preview-plus is installed and create an instance of that instead of the HTMLElement on line 6 in preview-element.js

> Seems like markdown-preview-plus-opener.coffee has most of the syntax that would be needed.

That would not make a lot of sense, HTMLElement on that line can't be replaced by an atom package.

> What to do?

To me it sounds like you want to opt-out of the default preview editor this package uses, and instead use the default text-editor, so the mentioned plugin works when you select a note, right? If yes then you'd need to change [the code that handles how the preview is opened and updated](https://github.com/viddo/atom-textual-velocity/blob/master/lib/side-effects.js#L163-L212). E.g. remove the preview editor, scheme stuff etc.

That said, this would be a separate feature/issue unrelated to this one, please open a separate issue if you'd like to continue discussing this.

**Comment by gotjoshua** [comment]
thanks @viddo 
actually the more i think about it:
i'd like to find a way to simply filter the content before sending it to _preview.updatePreview
discussion moved to my fork:
https://github.com/gotjoshua/atom-textual-velocity/issues/1
