### ISSUE TITLE
Refining auto activation

### ISSUE THREAD

**Issue by gotjoshua** [viddo/atom-textual-velocity#48]
I have two questions about the currently suggested auto activate code in the init config:

current coffescript:
```coffeescript
# Activate package right away
target = document.body.querySelector('atom-workspace')
atom.commands.dispatch(target, 'textual-velocity:start-session')
```
1) What is the difference between the target using querySelector and the following? and is one more appropriate or recommended by atom?
```coffeescript
target = atom.views.getView(atom.workspace)
```

2) Is there a way to test if there is already an active session in the current atom instance, and not try to start another session each time I open a new window?

**Comment by viddo** [comment]
1. Practically none, both yield the same result:
  ```js
  atom.views.getView(atom.workspace) === document.body.querySelector('atom-workspace') // => true
  ```
The closest thing to a recommendation that I've found is the official docs of [ViewRegistry#instance-getView](https://atom.io/docs/api/v1.12.7/ViewRegistry#instance-getView), which uses the latter. But the query selector is used in [quite some places](https://atom.io/docs/api/v1.12.7/ViewRegistry#instance-getView) where the actual view element is not needed/wanted, so I guess either works depending on what one needs.

If I recall correctly, the the mentioned doc page was written after I implemented the init script.

2. No, not easily at least. Atom provides no means to do that, one would have to implement some workaround to that oneself. I think the [discuss.atom.io](https://discuss.atom.io) is a better place for this kind of questions since it's not specific to this package, e.g. https://discuss.atom.io/t/detect-if-package-is-running-in-another-window/28078

**Comment by gotjoshua** [comment]
I agree that discussing the issue generically fits better over there.

Also I solved it using the lockfile approach that is mentioned over there: https://github.com/gotjoshua/atom-textual-velocity/pull/7/commits/48fbbdb01d6120bf777316cf370c53912d50accb

I chose to do this within the package rather than in my init. And I plan to add a package setting.
issue for discussion:
https://github.com/gotjoshua/atom-textual-velocity/issues/6

thoughts @viddo ?

**Comment by viddo** [comment]
I'm not entirely sure what kind of feedback you're really asking for, but I try to answer in the best way I can below with what I can read/see from here:

I still think it's something that shouldn't be part of the package itself, with the motivation that personal workflows/modifications are better suited in one's own init file. Of course you are free to do what you want in your own fork! I just wouldn't want to merge a PR with those changes back upstream.

**Comment by viddo** [comment]
I don't believe there is anything particular action to be done as part of this issue, so I'll go ahead and close it.
