### ISSUE TITLE
reads entire collection anew every time

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-textual-velocity#80]
Reporting a bug? Preferrably use the following format:

### Prerequisites

* [ x] Are you running the [latest version](https://github.com/viddo/atom-textual-velocity/releases)?
* [ x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+repo%3Aviddo%2Fatom-textual-velocity) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
Textual Velocity scans the directory and reads the entire collection anew every single time I start it.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**  read only changed notes, fast.

**Actual behavior:** takes about 5 minutes for 8000 notes

### Versions

Windows 10 64bit

**Comment by viddo** [comment]
Don't use/have Windows myself so will be a bit hard to troubleshoot. :/
There haven't been any changes to the caching mechanism in months, so not sure what could have provoked this. Let's see if we can narrow down the cause:

- What version of Atom are you using?
- Have the expected behavior worked for you previously? If so, have anything changed since then? E.g. updated Atom? Changed to Atom beta, etc.
- Can you check if you see any error/warning output in the devtools console (menu _View > Developer > Toggle developer tools_)?
- Does any of [debugging advice](http://flight-manual.atom.io/hacking-atom/sections/debugging/) help? In particular [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), [clearing saved state](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state), or [reset to factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)?
